### PR TITLE
use gdal to read shape files. update scan

### PR DESCRIPTION
**Pull request by voogt**

### CODE REVIEW

**Comment by lgkgh** [comment]
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 29 min

**Comment by NyakudyaA** [comment]
@voogt I assume this is what is deployed on the dev site now. It seems to still not work
image

**Comment by lgkgh** [comment]
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 27 min

**Comment by lgkgh** [comment]
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 15 min

**Pull request merged**
