### PR TITLE
Update scripts

### PR DESCRIPTION
**Pull request by NyakudyaA**
- [x] Add progress bar
- [x] Add ability to cancel alg
- [x] Fix duplicated country values in existing SQL
- [x] Fix strings with a single quote
- [x] Move all functions to be inside the class, making it easier to add feedback context etc

### CODE REVIEW

**Comment by lgkgh** [comment]
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 19 min

**Comment by lgkgh** [comment]
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 24 min

**Review by LunaAsefaw — COMMENTED** [review]
:+1:

**Comment by lgkgh** [comment]
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 22 min

**Pull request merged**
