### PR TITLE
Custom signup

### PR DESCRIPTION
**Pull request by voogt**
Adjust the signup page to be more informative #8

### CODE REVIEW

**Comment by lgkgh** [comment]
#### Jenkins Build Details:
**Build status:** FAILURE
**Build duration:** 1 min 9 sec

**Comment by voogt** [comment]
Hi @lgkgh @NyakudyaA the src directory includes the files I've updated of the GeoNode project. The code structure reflects what files needs to updated on the server. You can look at the src/readme.md for a better understanding

**Comment by lgkgh** [comment]
#### Jenkins Build Details:
**Build status:** FAILURE
**Build duration:** 1 min 27 sec

**Comment by lgkgh** [comment]
#### Jenkins Build Details:
**Build status:** FAILURE
**Build duration:** 1 min 15 sec

**Comment by lgkgh** [comment]
#### Jenkins Build Details:
**Build status:** FAILURE
**Build duration:** 11 min

**Pull request merged**
