### PR TITLE
Config update

### PR DESCRIPTION
**Pull request by voogt**

### CODE REVIEW

**Comment by lgkgh** [comment]
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 24 min

**Review by NyakudyaA — COMMENTED** [review]
@voogt What does this PR do ?

**Comment by voogt** [comment]
@NyakudyaA does not look like it made a difference so we can scrap this PR

**Comment by lgkgh** [comment]
#### Jenkins Build Details:
**Build status:** FAILURE
**Build duration:** 1 min 18 sec

**Pull request closed without merging**
