### PR TITLE
update docker files

### PR DESCRIPTION
**Pull request by voogt**

### CODE REVIEW

**Comment by NyakudyaA** [comment]
@voogt if the files are not being copied previously let's scrap this and I will copy them manually, it's a once off thing which we don't need to do all the time

**Comment by lgkgh** [comment]
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 25 min

**Comment by voogt** [comment]
@NyakudyaA apologies will fix this pull request now and reset it back to what it was previously before any update

**Comment by lgkgh** [comment]
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 16 min

**Pull request merged**
